apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: app
  name: app
spec:
  selector:
    matchLabels:
      component: app
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: app
    spec:
      containers:
        - image: ghcr.io/lolamtisch/bauclocom_kubernetes/cloudnextcloud:latest
          imagePullPolicy: Always
          name: app
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_HOST
              value: "mariadb-maxscale-connection"
            - name: REDIS_HOST
              value: "redis"
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: MYSQL_DATABASE
                  name: db-secrets
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: db-secrets
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: db-secrets
            - name: NEXTCLOUD_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  key: NEXTCLOUD_ADMIN_USER
                  name: db-secrets
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: NEXTCLOUD_ADMIN_PASSWORD
                  name: db-secrets
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              valueFrom:
                secretKeyRef:
                  key: NEXTCLOUD_TRUSTED_DOMAINS
                  name: db-secrets
            - name: OBJECTSTORE_S3_BUCKET
              value: "nextcloud"
            - name: OBJECTSTORE_S3_PORT
              value: "9000"
            - name: OBJECTSTORE_S3_SSL
              value: "false"
            - name: OBJECTSTORE_S3_USEPATH_STYLE
              value: "true"
            - name: OBJECTSTORE_S3_HOST
              value: "minio-hl"
            - name: OBJECTSTORE_S3_KEY
              valueFrom:
                secretKeyRef:
                  key: accesskey
                  name: minio-creds-secret
            - name: OBJECTSTORE_S3_SECRET
              valueFrom:
                secretKeyRef:
                  key: secretkey
                  name: minio-creds-secret
          volumeMounts:
            - mountPath: /var/www/html
              name: app-persistent-storage
      restartPolicy: Always
      volumes:
        - name: app-persistent-storage
          persistentVolumeClaim:
            claimName: app-pvc