apiVersion: minio.min.io/v1
kind: Tenant
metadata:
  creationTimestamp: null
  name: minio
scheduler:
  name: ""
spec:
  certConfig: {}
  console:
    consoleSecret:
      name: minio-console-secret
    image: minio/console:v0.4.6
    metadata:
      creationTimestamp: null
      name: minio
    replicas: 2
    resources: {}
  credsSecret:
    name: minio-creds-secret
  image: minio/minio:RELEASE.2020-12-10T01-54-29Z
  imagePullSecret: {}
  mountPath: /export
  requestAutoCert: false
  serviceName: minio-internal-service
  zones:
  - resources: {}
    servers: 2
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5G
        storageClassName: default
      status: {}
    volumesPerServer: 2
status:
  availableReplicas: 0
  currentState: ""
